title: Scrapinghub Learning Center
description: >
  Learn web scraping from the ground up with Scrapinghub's educational resources.
baseurl: "/learning-center" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scrapinghub
github_username:  scrapinghub

exclude:
  - Gemfile
  - Gemfile.lock
